export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const TOGGLE_ADDED_TO_CART = 'TOGGLE_CART_HIDDEN';
export const CLEAR_CART = 'CLEAR_CART';
export const MERGE_FROM_USER_CART = 'MERGE_FROM_USER_CART';
export const CART_ERROR = 'CART_ERROR';